version: "3"

services:
    db:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "33306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
        container_name: blog_db

    server:
        build:
            context: ./python/
            args:
                project_directory: "/blog/"
        ports:
            - "8080:8080"
        volumes:
            - "./python/blog:/projects"
        environment:
            TZ: "Asia/Tokyo"
        container_name: blog_python

    nginx:
        build: ./nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - server
        ports:
            - "80:80"
        environment:
            TZ: "Asia/Tokyo"
        container_name: "blog_nginx"